name: secrets

on:
  push:
    branches: main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Print all env
        run: python -c 'import sys,os,json;json.dump(dict(os.environ), sys.stdout)'
      - name: Print from secret
        run: echo "The env is ${{ secrets.DATABRICKS_TOKEN }} / ${{ secrets.DATABRICKS_HOST }}"
